-- ALTERAR TABELA GERENTE --
ALTER TABLE IF EXISTS gerente
	DROP COLUMN IF EXISTS codigo,
	ADD codigo VARCHAR(50) NOT NULL,
	DROP COLUMN IF EXISTS ativo,
	ADD ativo BOOLEAN NOT NULL;

-- ALTERAR TABELA VENDEDOR --
ALTER TABLE IF EXISTS vendedor
	DROP COLUMN IF EXISTS codigo,
	ADD codigo VARCHAR(50) NOT NULL,
	DROP COLUMN IF EXISTS ativo,
	ADD ativo BOOLEAN NOT NULL;

-- ALTERAR TABELA PRODUTO --
ALTER TABLE IF EXISTS produto
	DROP COLUMN IF EXISTS codigo_identificacao,
	ADD codigo_identificacao VARCHAR(50) NOT NULL;

-- ALTERAR TABELA promocao --
ALTER TABLE IF EXISTS nota_fiscal
	DROP COLUMN IF EXISTS codigo,
	ADD codigo VARCHAR(50) NOT NULL;